## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Imhotep Ben-Elliott Hogan"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

## Change to my social media accounts
[Params.social]
  github = "https://github.com/imhotephogan"
  twitter = "https://twitter.com/imhotepbhogan"
  email = "imhotep1.hogan@famu.edu"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"
